/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'Login.view.MyPanelViewModel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.container.ButtonGroup',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mypanel'
    },
    dock: 'top',
    height: 250,
    width: 400,
    title: '',

    layout: {
        type: 'vbox',
        align: 'stretch',
        pack: 'center'
    },
    bind: {
        flex: '1'
    },
    dockedItems: [
        {
            xtype: 'textareafield',
            dock: 'top',
            height: 62,
            itemId: 'username',
            fieldLabel: '',
            hideLabel: true,
            allowBlank: false,
            allowOnlyWhitespace: false,
            emptyText: 'Username',
            bind: {
                flex: '0.25'
            }
        },
        {
            xtype: 'textareafield',
            dock: 'top',
            itemId: 'password',
            emptyText: 'Password',
            bind: {
                flex: {
                    bindTo: '0.25',
                    deep: true
                }
            }
        },
        {
            xtype: 'toolbar',
            flex: 1,
            dock: 'top',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'buttongroup',
                    margins: '0',
                    border: true,
                    dock: 'top',
                    frame: false,
                    collapseFirst: false,
                    frameHeader: false,
                    header: false,
                    overlapHeader: false,
                    items: [
                        {
                            xtype: 'button',
                            scale: 'medium',
                            text: 'Reset'
                        },
                        {
                            xtype: 'button',
                            scale: 'medium',
                            text: 'Login'
                        }
                    ]
                }
            ]
        }
    ]

});