/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'Login.view.MyViewportViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Spacer',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table'
    ],

    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    scrollable: 'vertical',
    width: 400,

    items: [
        {
            xtype: 'panel',
            bodyPadding: 35,
            title: 'Search Booking',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    width: 848,
                    items: [
                        {
                            xtype: 'tbfill',
                            dock: 'right'
                        },
                        {
                            xtype: 'button',
                            allowDepress: false,
                            scale: 'medium',
                            text: 'Search'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Booking',
                            size: 60
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Container',
                            size: 60
                        },
                        {
                            xtype: 'combobox',
                            modelValidation: true,
                            fieldLabel: 'Status',
                            size: 60,
                            displayField: 'Key',
                            queryMode: 'local',
                            store: 'MyArrayStore',
                            valueField: 'Value'
                        }
                    ]
                },
                {
                    xtype: 'tbspacer',
                    flex: 0.5,
                    maxWidth: 200,
                    width: 166
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: '',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'From',
                            size: 60
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'To',
                            size: 60
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'tabpanel',
            bodyPadding: 5,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    bodyBorder: false,
                    bodyPadding: 20,
                    title: 'Booking Details',
                    tabConfig: {
                        xtype: 'tab',
                        padding: 5
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            titleCollapse: false,
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Booking Number'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Shipper'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Consignee'
                                }
                            ],
                            viewConfig: {
                                height: 100
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    border: true,
                    bodyPadding: 20,
                    title: 'Container Details',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    padding: 8,
                                    fieldLabel: 'Cargo Nature',
                                    size: 60
                                },
                                {
                                    xtype: 'tbspacer',
                                    maxWidth: 300,
                                    width: 300
                                },
                                {
                                    xtype: 'textfield',
                                    padding: 8,
                                    fieldLabel: 'Cargo Desc',
                                    size: 60
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            margin: 15,
                            bodyBorder: true,
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Container Number'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'Container Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'Gross Weight'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'Net Weight'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'From'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'To'
                                }
                            ],
                            viewConfig: {
                                height: 105
                            }
                        }
                    ],
                    tabConfig: {
                        xtype: 'tab',
                        padding: 5
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    scale: 'medium',
                    text: 'Update'
                }
            ]
        }
    ]

});