/*
 * File: app/view/StatusesViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.StatusesViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.statuses',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        statuses: {
            model: 'Login.model.Status',
            data: [
                {
                    Active: 'cupiditate',
                    Inactive: 'debitis'
                },
                {
                    Active: 'dolor',
                    Inactive: 'et'
                },
                {
                    Active: 'excepturi',
                    Inactive: 'dolor'
                },
                {
                    Active: 'et',
                    Inactive: 'necessitatibus'
                },
                {
                    Active: 'possimus',
                    Inactive: 'modi'
                },
                {
                    Active: 'doloribus',
                    Inactive: 'quo'
                },
                {
                    Active: 'libero',
                    Inactive: 'officiis'
                },
                {
                    Active: 'molestiae',
                    Inactive: 'deleniti'
                },
                {
                    Active: 'qui',
                    Inactive: 'corrupti'
                },
                {
                    Active: 'natus',
                    Inactive: 'ea'
                },
                {
                    Active: 'in',
                    Inactive: 'quis'
                },
                {
                    Active: 'ut',
                    Inactive: 'nihil'
                },
                {
                    Active: 'rem',
                    Inactive: 'dolor'
                },
                {
                    Active: 'nihil',
                    Inactive: 'earum'
                },
                {
                    Active: 'ut',
                    Inactive: 'vel'
                },
                {
                    Active: 'fugiat',
                    Inactive: 'error'
                },
                {
                    Active: 'eum',
                    Inactive: 'et'
                },
                {
                    Active: 'modi',
                    Inactive: 'qui'
                },
                {
                    Active: 'consectetur',
                    Inactive: 'dolorem'
                },
                {
                    Active: 'minima',
                    Inactive: 'cum'
                },
                {
                    Active: 'soluta',
                    Inactive: 'qui'
                },
                {
                    Active: 'aut',
                    Inactive: 'repellendus'
                },
                {
                    Active: 'exercitationem',
                    Inactive: 'sed'
                },
                {
                    Active: 'dolor',
                    Inactive: 'doloribus'
                },
                {
                    Active: 'eos',
                    Inactive: 'molestias'
                },
                {
                    Active: 'tempora',
                    Inactive: 'qui'
                },
                {
                    Active: 'aspernatur',
                    Inactive: 'amet'
                },
                {
                    Active: 'sit',
                    Inactive: 'esse'
                },
                {
                    Active: 'nihil',
                    Inactive: 'architecto'
                },
                {
                    Active: 'quibusdam',
                    Inactive: 'nesciunt'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});