/*
 * File: app/store/CntrTypeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.store.CntrTypeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Booking.model.CntrTypeModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CntrTypeStore',
            model: 'Booking.model.CntrTypeModel',
            data: [
                {
                    name: '20GP',
                    code: '20GP'
                },
                {
                    name: '40GP',
                    code: '40GP'
                },
                {
                    name: '20HQ',
                    code: '20HQ'
                },
                {
                    name: '40HQ',
                    code: '40HQ'
                },
                {
                    name: '45HQ',
                    code: '45HQ'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});