/*
 * File: app/view/ListUser.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.view.ListUser', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.listuser',

    requires: [
        'Booking.view.ListUserViewModel',
        'Booking.view.ListUserViewController',
        'Ext.Img',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.container.ButtonGroup',
        'Ext.button.Button'
    ],
    controller:'listuser',
    viewModel: {
        type: 'listuser'
    },
    width: 400,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
    	{
            xtype: 'container',
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                    	{
                            xtype: 'image',
                            flex: 1,
                            dock: 'top',
                            height: '',
                            maxHeight: 80,
                            maxWidth: 200,
                            src: 'brand.png'
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                            	 {
                                     xtype: 'button',
                                     id: 'userButton1',
                                     itemId: 'userButton1',
                                     allowDepress: false,
                                     scale: 'medium',
                                     text: 'User',
                                     listeners: {
                                         'beforerender' : function() {
                                         	 Ext.Ajax.request({
                                   				url : 'user/getAuth',
                                   				method : 'POST',
                                   				scope : this,
                                   				success : function(response) {
                                   					if(response.responseText == "3" || response.responseText == "2") Ext.getCmp('userButton').hide();
                                   				}
                                   			});	
                                         }
                                     }
                                 },
                            	 {
                                     xtype: 'button',
                                     id: 'searchButton2',
                                     itemId: 'searchButton2',
                                     allowDepress: false,
                                     scale: 'medium',
                                     text: 'Booking'
                                 },
                                 {
                                     xtype: 'button',
                                     id: 'logOut2',
                                     scale: 'medium',
                                     text: 'Logout'
                                 }
                            ]
                        }
                    ]
                }]},
        {
            xtype: 'container',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    title: 'User List',
                    id:'userList',
                    itemId:'userList',
                    forceFit: true,
                    store: 'UserStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Username',
                            id: 'userNameField',
                            text: 'Username'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Password',
                            id: 'passwordField',
                            text: 'Password'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Role',
                            id: 'roleField',
                            text: 'Role'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Email',
                            id: 'emailField',
                            text: 'Email'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FirstName',
                            id: 'firstNameField',
                            text: 'First Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'LastName',
                            id: 'lastNameField',
                            text: 'Last Name'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            ui: 'footer',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'buttongroup',
                                    border: false,
                                    frame: false,
                                   columns: 4,
                                    items: [
                                    	{
                                            xtype: 'button',
                                            id: 'searchUser',
                                            itemId: 'searchUser',
                                            text: 'List'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'addUser',
                                            itemId: 'addUser',
                                            text: 'Add',
                                            listeners: {
                                            	click: 'onAddUser'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'updateUser',
                                            itemId: 'updateUser',
                                            text: 'Update',
                                            listeners: {
                                            	click: 'onUpdateUser'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'deleteUser',
                                            itemId: 'deleteUser',
                                            text: 'Delete', 
                                            listeners: {
                                            	click: 'onDeleteUser'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});