/*
 * File: app/view/loginWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.loginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginWindow',

    requires: [
        'Login.view.loginWindowViewModel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.container.ButtonGroup',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'loginwindow'
    },
    autoShow: true,
    draggable: false,
    height: 192,
    padding: 20,
    resizable: false,
    width: 400,
    closable: false,
    placeholderCollapseHideMode: 3,
    title: '',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    dockedItems: [
        {
            xtype: 'textfield',
            dock: 'top',
            height: 30,
            itemId: 'username',
            margin: 10,
            maxHeight: 30,
            emptyText: 'Username'
        },
        {
            xtype: 'textfield',
            dock: 'top',
            height: 30,
            itemId: 'password',
            inputType: 'password',
            margin: 10,
            maxHeight: 30,
            fieldLabel: '',
            emptyText: 'Password',
            size: 15
        },
        {
            xtype: 'toolbar',
            modal: true,
            border: 3,
            dock: 'bottom',
            height: 56,
            shrinkWrap: 3,
            width: 400,
            trackMenus: false,
            layout: {
                type: 'hbox',
                pack: 'end'
            },
            items: [
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'buttongroup',
                    border: false,
                    frame: false,
                    items: [
                        {
                            xtype: 'button',
                            modal: true,
                            scale: 'medium',
                            text: 'Reset'
                        },
                        {
                            xtype: 'button',
                            modal: true,
                            enableToggle: true,
                            pressed: true,
                            scale: 'medium',
                            text: 'Login'
                        }
                    ]
                }
            ]
        }
    ]

});