CREATE SEQUENCE gs_user_seq
 START WITH     1
 INCREMENT BY   1;
 
 CREATE SEQUENCE gs_booking_seq
 START WITH     4000000000
 INCREMENT BY   1;
 
 CREATE SEQUENCE gs_container_seq
 START WITH     1
 INCREMENT BY   1;