/*
 * File: app/controller/DeleteUserController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.controller.DeleteUserController', {
    extend: 'Ext.app.Controller',

    control: {
        "#deleteUser": {
            click: 'onDeleteUserClick'
        }
    },

    onDeleteUserClick: function(button, e, eOpts) {
    	Ext.Ajax.request({
			url : 'booking/search',
			method : 'POST',
			datatype : 'json',
			params : {
				criteria: Ext.util.JSON.encode(criteria)
			},
			scope : this,
			success : function(response) {
				
			
			}
    	});
    }
});
