/*
 * File: app/controller/LogInController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.controller.LogInController', {
	extend : 'Ext.app.Controller',

	config : {
		refs : [ 
			{
				ref : 'username',
				selector : 'loginWindow #username'
			},
			{
				ref : 'password',
				selector : 'loginWindow #password'
			},
		]
	},
	control : {
		"#mybutton1" : {
			click : 'onMybutton1Click'
		}
	},

	onMybutton1Click : function(button, e, eOpts) {

		Ext.getCmp("username").getValue();
		Ext.Ajax.request({
			url : 'login',
			method : 'POST',
			params : {
				username : this.getUsername().getValue(),
				password : this.getPassword().getValue()
			},
			scope : this,
			success : function(response) {
				var data = Ext.decode(response.responseText);
//				console.log(data);
//				if(!data.success)
//				Ext.Msg.alert('not found', 'olol');
//				else{
//					Ext.getCmp("loginWindow").hide();
//					Ext.create("Booking.view.SearchBookingView").show();
//				}
			}
		});
	}

});
