/*
 * File: app/controller/LogOutController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.controller.LogOutController', {
    extend: 'Ext.app.Controller',

    id: 'LogOutController',

    control: {
        "#logOut": {
            click: 'onLogOutClick'
        }
    },

    onLogOutClick: function(button, e, eOpts) {
    	Ext.getBody().mask();
    	Ext.create('Ext.window.Window', {
            title: 'User Logout',
            id: 'LogoutWndowId',
            layout: {
            	type: 'vbox',
                align: 'stretch'
            },
            width: 250,
            height: 100,
            listeners: {
                close: {
                    scope: this,
                    fn: function () {
                    	Ext.getBody().unmask();
                    	window.location.reload();
                        var win = Ext.getCmp('LogoutWndowId');
                        win.destroy();
                    }
                }
            },
            items: [
            	{
            		 xtype: 'container',
                     id: 'LogoutWndowContainrId',
                     padding: '10',
                     layout: {
                         type: 'vbox',
                         align: 'stretch'
                     },
                     items: [
                    	 {
		            		xtype: 'label',
		                    text: 'You have successfully logged out.'
                    	 },
                    	 {
                    		 xtype: 'button',
                             text: 'Confirm',
                             listeners: {
                                 click: {
                                	 scope: this,
                                	 fn: function(){
                                		Ext.Ajax.request({
                                  			url : 'logout',
                                  			params : { },
                                  			scope : this,
                                  			success : function(response) {
                                  				//setTimeout(function() { window.location.reload(); }, 1000);
                                  				Ext.getCmp('LogoutWndowId').close();
                                  				window.location.reload();
                                  			}
                                      	});
                                	 }
                                 }
                             }
                    	 }
                    ]
            	}
            ]
		}).show();
    }

});
