/*
 * File: app/controller/LogOutController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.controller.LogOutController', {
    extend: 'Ext.app.Controller',

    id: 'LogOutController',

    control: {
        "#logOut": {
            click: 'onLogOutClick'
        }
    },

    onLogOutClick: function(button, e, eOpts) {
    	Ext.Ajax.request({
			url : 'logout',
			params : {
			},
			scope : this,
			success : function(response) {
				 Ext.Msg.alert('Logout','You have successfully logged out');
//				alert('You have successfully logged out');
				setTimeout(function() { window.location.reload(); }, 3000);
				
				}
		});
    }

});
