/*
 * File: app/controller/SearchController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.controller.SearchController', {
	extend : 'Ext.app.Controller',

	control : {
		"#searchButton1" : {
			click : 'onSearchButtonClick'
		}
	},

	onSearchButtonClick : function(button, e, eOpts) {
		var store = Ext.getStore('BkgStore');

		Ext.Ajax.request({
			url : 'booking/listBkg',
			method : 'POST',
			datatype : 'json',
			params : {

			},
			scope : this,
			success : function(response) {
				var data = Ext.decode(response.responseText);
				Ext.each(data, function(record) {
					var books = {
							BkgNum : record.bkgNum,
				            Shipper : record.shipper,
				            Consignee : record.consignee,
				            From : record.fromCity,
				    		To : record.toCity
					};
					store.add(books);
				});
			}
		});
	}

});
