/*
 * File: app/model/Status.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.model.Status', {
    extend: 'Ext.data.Model',
    alias: 'model.status',

    requires: [
        'Ext.data.field.String'
    ],
    uses: [
        'Login.model.Status'
    ],

    fields: [
        {
            type: 'string',
            defaultValue: 'Active',
            mapping: 'key',
            name: 'Key',
            persist: false,
            reference: 'Login.model.Status'
        },
        {
            type: 'string',
            name: 'Value'
        }
    ]
});