/*
 * File: app/view/ListUser.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Booking.view.ListUser', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.listuser',

    requires: [
        'Booking.view.ListUserViewModel',
        'Ext.Img',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.container.ButtonGroup',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'listuser'
    },
    width: 400,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'image',
            dock: 'top',
            height: '',
            maxHeight: 45,
            maxWidth: 100,
            src: 'brand.png'
        },
        {
            xtype: 'container',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 0.5,
                    title: 'User List',
                    forceFit: true,
                    store: 'UserStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Username',
                            text: 'Username'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Password',
                            text: 'Password'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            ui: 'footer',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'buttongroup',
                                    border: false,
                                    frame: false,
                                    columns: 2,
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'addUser',
                                            itemId: 'addUser',
                                            text: 'Add'
                                        },
                                        {
                                            xtype: 'button',
                                            id: 'deleteUser',
                                            itemId: 'deleteUser',
                                            text: 'Delete'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});